In [1]:
pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\rosas\appdata\local\programs\python\python314\lib\site-packages (1.2.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
# importamos librerías necesarias 

import pandas as pd
import json
import requests
import os # no hay que instalarlo
from dotenv import load_dotenv # esta es una librería para poder encriptar nuestra api_key

## Extracción de canciones en JSON

In [24]:
# usamos la forma json para acceder a la base de datos

with open('definitivo.json') as archivo:
    data = json.load(archivo)

In [25]:
canciones_pop_2010_2015 = []

anios = [2013, 2014, 2015]
genres = ['pop']

for cancion in data:
    if cancion['genre'] in genres:
        if cancion['year'] in anios:
            canciones_pop_2010_2015.append(cancion)

canciones_pop_2010_2015

[{'id': '3U4isOIWM3VvDubwSI3y7a',
  'artist_name': 'John Legend',
  'track_name': 'All of Me',
  'genre': 'pop',
  'year': 2013},
 {'id': '6Al0Kpd4VrRZ0Z4kTThNPa',
  'artist_name': 'Carlos Vives',
  'track_name': 'Volví a Nacer',
  'genre': 'pop',
  'year': 2013},
 {'id': '3ozuHMral4k7ALNOgPdxQ8',
  'artist_name': 'La Oreja de Van Gogh',
  'track_name': 'El Primer Día del Resto de Mi Vida - Directo Primera Fila',
  'genre': 'pop',
  'year': 2013},
 {'id': '26Z2FQ9KFswyX2x7LxhQKs',
  'artist_name': 'INNA',
  'track_name': 'Caliente',
  'genre': 'pop',
  'year': 2013},
 {'id': '2XHzzp1j4IfTNp1FTn7YFg',
  'artist_name': 'Lil Wayne',
  'track_name': 'Love Me',
  'genre': 'pop',
  'year': 2013},
 {'id': '2XHzzp1j4IfTNp1FTn7YFg',
  'artist_name': 'Drake',
  'track_name': 'Love Me',
  'genre': 'pop',
  'year': 2013},
 {'id': '2XHzzp1j4IfTNp1FTn7YFg',
  'artist_name': 'Future',
  'track_name': 'Love Me',
  'genre': 'pop',
  'year': 2013},
 {'id': '2JkJ0E1KFU6HatD5Y21YfX',
  'artist_name': 'Sergio Contreras',
  'track_name': 'Princesa de mi cuento',
  'genre': 'pop',
  'year': 2013},
 {'id': '7ccRZaWMrVZngBqD1ImOrG',
  'artist_name': 'INNA',
  'track_name': 'More Than Friends',
  'genre': 'pop',
  'year': 2013},
 {'id': '7ccRZaWMrVZngBqD1ImOrG',
  'artist_name': 'Daddy Yankee',
  'track_name': 'More Than Friends',
  'genre': 'pop',
  'year': 2013},
 {'id': '2y4lAQpi5VTNLu2ldeTdUH',
  'artist_name': 'Miley Cyrus',
  'track_name': "We Can't Stop",
  'genre': 'pop',
  'year': 2013},
 {'id': '2iJuuzV8P9Yz0VSurttIV5',
  'artist_name': 'will.i.am',
  'track_name': 'Scream & Shout',
  'genre': 'pop',
  'year': 2013},
 {'id': '2iJuuzV8P9Yz0VSurttIV5',
  'artist_name': 'Britney Spears',
  'track_name': 'Scream & Shout',
  'genre': 'pop',
  'year': 2013},
 {'id': '2U8NXPTXZWG2O0ye2sYRiH',
  'artist_name': 'Icona Pop',
  'track_name': 'I Love It (feat. Charli XCX)',
  'genre': 'pop',
  'year': 2013},
 {'id': '2U8NXPTXZWG2O0ye2sYRiH',
  'artist_name': 'Charli xcx',
  'track_name': 'I Love It (feat. Charli XCX)',
  'genre': 'pop',
  'year': 2013},
 {'id': '4hc0VETiFO91s9yiXvgaUp',
  'artist_name': 'Fly Project',
  'track_name': 'Toca Toca - Radio Edit',
  'genre': 'pop',
  'year': 2013},
 {'id': '6jizk5lOUnfpaZXYMdfeC6',
  'artist_name': 'Jason Derulo',
  'track_name': 'Trumpets',
  'genre': 'pop',
  'year': 2013},
 {'id': '484nwuYjpSZmR4eqaNB0CR',
  'artist_name': 'Nolasco',
  'track_name': 'Futuro Imperfecto',
  'genre': 'pop',
  'year': 2013},
 {'id': '1V6gIisPpYqgFeWbMLI0bA',
  'artist_name': 'Demi Lovato',
  'track_name': 'Heart Attack',
  'genre': 'pop',
  'year': 2013},
 {'id': '5ka2ajep9OAvU5Sgduhiex',
  'artist_name': 'Lady Gaga',
  'track_name': 'Applause',
  'genre': 'pop',
  'year': 2013},
 {'id': '1yjY7rpaAQvKwpdUliHx0d',
  'artist_name': 'Paramore',
  'track_name': 'Still into You',
  'genre': 'pop',
  'year': 2013},
 {'id': '06PapYCtVDlprJPgGELabn',
  'artist_name': 'BTS',
  'track_name': 'Attack on Bangtan',
  'genre': 'pop',
  'year': 2013},
 {'id': '6LoQHIo74tOzQ8EsLEkhgF',
  'artist_name': 'Selena Gomez',
  'track_name': 'Come & Get It',
  'genre': 'pop',
  'year': 2013},
 {'id': '3KliPMvk1EvFZu9cvkj8p1',
  'artist_name': 'Britney Spears',
  'track_name': 'Work Bitch',
  'genre': 'pop',
  'year': 2013},
 {'id': '089PFeXotzDLNQz9NCk6pF',
  'artist_name': 'BTS',
  'track_name': 'No More Dream',
  'genre': 'pop',
  'year': 2013},
 {'id': '1w5FE5HRovp8oBwMDU3i1h',
  'artist_name': 'Los Caños',
  'track_name': 'Niña Piensa en Tí',
  'genre': 'pop',
  'year': 2013},
 {'id': '1ntOYOoGOutpWhCSQTn8KJ',
  'artist_name': 'India Martinez',
  'track_name': 'Los Gatos No Ladran',
  'genre': 'pop',
  'year': 2013},
 {'id': '0SOgw04C2ps0lZsVov0vHN',
  'artist_name': 'Passenger',
  'track_name': 'Let Her Go - Acoustic',
  'genre': 'pop',
  'year': 2013},
 {'id': '6OPZtIV3uoZQT1YkoiEQH9',
  'artist_name': 'Jason Derulo',
  'track_name': 'The Other Side',
  'genre': 'pop',
  'year': 2013},
 {'id': '0S4RKPbRDA72tvKwVdXQqe',
  'artist_name': 'Ariana Grande',
  'track_name': 'The Way',
  'genre': 'pop',
  'year': 2013},
 {'id': '0S4RKPbRDA72tvKwVdXQqe',
  'artist_name': 'Mac Miller',
  'track_name': 'The Way',
  'genre': 'pop',
  'year': 2013},
 {'id': '3VFr9JYb6ppsl4yxwerUXq',
  'artist_name': 'Gregory Porter',
  'track_name': 'Hey Laura',
  'genre': 'pop',
  'year': 2013},
 {'id': '55Ctj6nVfobn9AcPe6sLG2',
  'artist_name': 'BTS',
  'track_name': 'Like',
  'genre': 'pop',
  'year': 2013},
 {'id': '5XKXMWPACPq51OiqzxenZo',
  'artist_name': 'Lady Gaga',
  'track_name': 'Do What U Want',
  'genre': 'pop',
  'year': 2013},
 {'id': '5XKXMWPACPq51OiqzxenZo',
  'artist_name': 'Christina Aguilera',
  'track_name': 'Do What U Want',
  'genre': 'pop',
  'year': 2013},
 {'id': '2wDiktMejILuXe3rSy2DHV',
  'artist_name': 'Gloria Trevi',
  'track_name': 'No Querías Lastimarme',
  'genre': 'pop',
  'year': 2013},
 {'id': '2X6b7zLdIxCejd6GqVcQ9M',
  'artist_name': 'Childish Gambino',
  'track_name': '3005',
  'genre': 'pop',
  'year': 2013},
 {'id': '7EDlJ1ESbCIACkRPjZbdRL',
  'artist_name': 'María Artés',
  'track_name': 'Si tú supieras',
  'genre': 'pop',
  'year': 2013},
 {'id': '4renR4qHSuEPMtuvbKirNz',
  'artist_name': 'María Artés',
  'track_name': 'Mi sentimiento',
  'genre': 'pop',
  'year': 2013},
 {'id': '4rYLpaNFzt6pkQnrCvVHUw',
  'artist_name': 'Lady Gaga',
  'track_name': 'G.U.Y.',
  'genre': 'pop',
  'year': 2013},
 {'id': '2OsEJFTfzfjG4oC92cuP2c',
  'artist_name': 'Selena Gomez',
  'track_name': 'Slow Down',
  'genre': 'pop',
  'year': 2013},
 {'id': '5pjHS3EpHurMyIpB2QBnEd',
  'artist_name': 'BTS',
  'track_name': 'We Are Bulletproof Pt.2',
  'genre': 'pop',
  'year': 2013},
 {'id': '15iosIuxC3C53BgsM5Uggs',
  'artist_name': 'Icona Pop',
  'track_name': 'All Night',
  'genre': 'pop',
  'year': 2013},
 {'id': '4MKO1xltVSQlMMZUfOMEA1',
  'artist_name': 'London Grammar',
  'track_name': 'Nightcall',
  'genre': 'pop',
  'year': 2013},
 {'id': '0NjW4SKY3gbfl2orl1p8hr',
  'artist_name': 'Tyler, The Creator',
  'track_name': 'IFHY (feat. Pharrell)',
  'genre': 'pop',
  'year': 2013},
 {'id': '0NjW4SKY3gbfl2orl1p8hr',
  'artist_name': 'Pharrell Williams',
  'track_name': 'IFHY (feat. Pharrell)',
  'genre': 'pop',
  'year': 2013},
 {'id': '5x0j5GEuf4AjJSVeiQrRTu',
  'artist_name': 'PSY',
  'track_name': 'Gentleman',
  'genre': 'pop',
  'year': 2013},
 {'id': '1j8z4TTjJ1YOdoFEDwJTQa',
  'artist_name': 'Paramore',
  'track_name': "Ain't It Fun",
  'genre': 'pop',
  'year': 2013},
 {'id': '2ZY4JhvBJftNIXigwCbGhw',
  'artist_name': 'Nicolas Mayorca',
  'track_name': 'Mi Canción (feat. Cali Y El Dandee)',
  'genre': 'pop',
  'year': 2013},
 {'id': '2ZY4JhvBJftNIXigwCbGhw',
  'artist_name': 'Cali Y El Dandee',
  'track_name': 'Mi Canción (feat. Cali Y El Dandee)',
  'genre': 'pop',
  'year': 2013},
 {'id': '55klEU4KKofUQidwkb6INX',
  'artist_name': 'INNA',
  'track_name': 'In Your Eyes',
  'genre': 'pop',
  'year': 2013},
 {'id': '5vTPxzm4h2bY9rYyVrGEU5',
  'artist_name': 'Demi Lovato',
  'track_name': "Really Don't Care",
  'genre': 'pop',
  'year': 2013},
 {'id': '5vTPxzm4h2bY9rYyVrGEU5',
  'artist_name': 'Cher Lloyd',
  'track_name': "Really Don't Care",
  'genre': 'pop',
  'year': 2013},
 {'id': '2DHDuADAHoUW6n0z80RLQF',
  'artist_name': 'Andrew Belle',
  'track_name': 'Pieces',
  'genre': 'pop',
  'year': 2013},
 {'id': '7JosxtkCqIQieNWXA2Dj3v',
  'artist_name': 'BTS',
  'track_name': 'N.O',
  'genre': 'pop',
  'year': 2013},
 {'id': '2FHdoPa5aWaAmjuf362KJ0',
  'artist_name': 'Jennifer Lopez',
  'track_name': 'Live It Up',
  'genre': 'pop',
  'year': 2013},
 {'id': '2FHdoPa5aWaAmjuf362KJ0',
  'artist_name': 'Pitbull',
  'track_name': 'Live It Up',
  'genre': 'pop',
  'year': 2013},
 {'id': '39z2CyYexbcwgD0pEeUUeu',
  'artist_name': 'Rich Gang',
  'track_name': 'Tapout',
  'genre': 'pop',
  'year': 2013},
 {'id': '39z2CyYexbcwgD0pEeUUeu',
  'artist_name': 'Lil Wayne',
  'track_name': 'Tapout',
  'genre': 'pop',
  'year': 2013},
 {'id': '39z2CyYexbcwgD0pEeUUeu',
  'artist_name': 'Birdman',
  'track_name': 'Tapout',
  'genre': 'pop',
  'year': 2013},
 {'id': '39z2CyYexbcwgD0pEeUUeu',
  'artist_name': 'Mack Maine',
  'track_name': 'Tapout',
  'genre': 'pop',
  'year': 2013},
 {'id': '39z2CyYexbcwgD0pEeUUeu',
  'artist_name': 'Nicki Minaj',
  'track_name': 'Tapout',
  'genre': 'pop',
  'year': 2013},
 {'id': '39z2CyYexbcwgD0pEeUUeu',
  'artist_name': 'Future',
  'track_name': 'Tapout',
  'genre': 'pop',
  'year': 2013},
 {'id': '48FYeyIwp26ndvx9IRv8TE',
  'artist_name': 'Edward Maya',
  'track_name': 'Stereo Love',
  'genre': 'pop',
  'year': 2013},
 {'id': '48FYeyIwp26ndvx9IRv8TE',
  'artist_name': 'Vika Jigulina',
  'track_name': 'Stereo Love',
  'genre': 'pop',
  'year': 2013},
 {'id': '5MKPXztfYrhzgZkkk6zT4N',
  'artist_name': 'El Suso',
  'track_name': 'Quiere Ser Libre (feat. La Húngara)',
  'genre': 'pop',
  'year': 2013},
 {'id': '5MKPXztfYrhzgZkkk6zT4N',
  'artist_name': 'La Húngara',
  'track_name': 'Quiere Ser Libre (feat. La Húngara)',
  'genre': 'pop',
  'year': 2013},
 {'id': '4eqHEzFsCCiGALC1MHbqnU',
  'artist_name': 'BTS',
  'track_name': 'Coffee',
  'genre': 'pop',
  'year': 2013},
 {'id': '3n3S5cH3IyaOswY2XSUGTS',
  'artist_name': 'Lady Gaga',
  'track_name': 'Venus',
  'genre': 'pop',
  'year': 2013},
 {'id': '42rtLutZjrQGmzxZhN5YFA',
  'artist_name': 'La Oreja de Van Gogh',
  'track_name': 'Deseos de Cosas Imposibles (with Abel Pintos) - Directo Primera Fila',
  'genre': 'pop',
  'year': 2013},
 {'id': '42rtLutZjrQGmzxZhN5YFA',
  'artist_name': 'Abel Pintos',
  'track_name': 'Deseos de Cosas Imposibles (with Abel Pintos) - Directo Primera Fila',
  'genre': 'pop',
  'year': 2013},
 {'id': '1dlvCR47icv2BCiBCSF204',
  'artist_name': "Beluga's Trio",
  'track_name': "It Ain't over Til' It's Over",
  'genre': 'pop',
  'year': 2013},
 {'id': '1dlvCR47icv2BCiBCSF204',
  'artist_name': 'Celso Mendes',
  'track_name': "It Ain't over Til' It's Over",
  'genre': 'pop',
  'year': 2013},
 {'id': '6nyZQ82OI0OujbbFpo3e0K',
  'artist_name': 'John Legend',
  'track_name': 'All of Me - Live from Spotify Milan',
  'genre': 'pop',
  'year': 2013},
 {'id': '7C5l5hLxS4uZX1VJR13ZBT',
  'artist_name': 'Miguel Bosé',
  'track_name': 'Si tú no vuelves',
  'genre': 'pop',
  'year': 2013},
 {'id': '1zVhMuH7agsRe6XkljIY4U',
  'artist_name': 'Christina Perri',
  'track_name': 'human',
  'genre': 'pop',
  'year': 2013},
 {'id': '0pqCMHN3IVkBDlWAg0kiVa',
  'artist_name': 'SEREBRO',
  'track_name': 'Mi Mi Mi',
  'genre': 'pop',
  'year': 2013},
 {'id': '7JmIjOsRish3vYBSLTytEC',
  'artist_name': 'Ariana Grande',
  'track_name': 'Tattooed Heart',
  'genre': 'pop',
  'year': 2013},
 {'id': '6ToFxXRBtl5TJFEyIoYK3f',
  'artist_name': 'Justin Timberlake',
  'track_name': 'Mirrors - Radio Edit',
  'genre': 'pop',
  'year': 2013},
 {'id': '1KbX1VuFIgsRa9JjnQtRYA',
  'artist_name': 'Carlos Vives',
  'track_name': 'Bailar Contigo',
  'genre': 'pop',
  'year': 2013},
 {'id': '5zvJELVKAnPkscGc5aLKJI',
  'artist_name': 'James Arthur',
  'track_name': 'Certain Things (feat. Chasing Grace)',
  'genre': 'pop',
  'year': 2013},
 {'id': '5zvJELVKAnPkscGc5aLKJI',
  'artist_name': 'Chasing Grace',
  'track_name': 'Certain Things (feat. Chasing Grace)',
  'genre': 'pop',
  'year': 2013},
 {'id': '4kiCjwxqO47NEfr5kdPG3A',
  'artist_name': 'Sergio Contreras',
  'track_name': '#Amor (feat. Fernando Caro)',
  'genre': 'pop',
  'year': 2013},
 {'id': '6NmCCgnQcxKHPOAKgd9Nth',
  'artist_name': 'Ariana Grande',
  'track_name': 'Baby I',
  'genre': 'pop',
  'year': 2013},
 {'id': '34MJ07N9Bhu6iKPaxSVnCT',
  'artist_name': 'Demi Lovato',
  'track_name': 'Neon Lights',
  'genre': 'pop',
  'year': 2013},
 {'id': '3fibIzbkYbvTmdoD5u2nPm',
  'artist_name': 'Lady Gaga',
  'track_name': 'Aura',
  'genre': 'pop',
  'year': 2013},
 {'id': '5SmXEPnevlRjBPWBG7oKIi',
  'artist_name': 'Ariana Grande',
  'track_name': 'Honeymoon Avenue',
  'genre': 'pop',
  'year': 2013},
 {'id': '1JVf7tzhspVTRrRHxiJhD5',
  'artist_name': 'Michael Bublé',
  'track_name': 'To Love Somebody',
  'genre': 'pop',
  'year': 2013},
 {'id': '73zDQykFwu3yT5VQ6MwYbh',
  'artist_name': 'Lady Gaga',
  'track_name': 'ARTPOP',
  'genre': 'pop',
  'year': 2013},
 {'id': '0tSE3FNeqYVuTQIy1s67Az',
  'artist_name': 'Miguel Bosé',
  'track_name': 'Morena mía',
  'genre': 'pop',
  'year': 2013},
 {'id': '59ItlxP6jInKKJvviwJQu4',
  'artist_name': 'Fondo Flamenco',
  'track_name': 'El Salon',
  'genre': 'pop',
  'year': 2013},
 {'id': '7zMqrnUGpJE4IQ4LaGMx7N',
  'artist_name': 'Silver Pozzoli',
  'track_name': 'Around My Dream',
  'genre': 'pop',
  'year': 2013},
 {'id': '4N3q8LWLrPstV5FoqJXyrj',
  'artist_name': 'María Artés',
  'track_name': 'Eres mi amor (feat. Demarco)',
  'genre': 'pop',
  'year': 2013},
 {'id': '26XUAwGZqQEyy8Ubhtj4kq',
  'artist_name': 'will.i.am',
  'track_name': "Feelin' Myself",
  'genre': 'pop',
  'year': 2013},
 {'id': '26XUAwGZqQEyy8Ubhtj4kq',
  'artist_name': 'Miley Cyrus',
  'track_name': "Feelin' Myself",
  'genre': 'pop',
  'year': 2013},
 {'id': '26XUAwGZqQEyy8Ubhtj4kq',
  'artist_name': 'French Montana',
  'track_name': "Feelin' Myself",
  'genre': 'pop',
  'year': 2013},
 {'id': '26XUAwGZqQEyy8Ubhtj4kq',
  'artist_name': 'Wiz Khalifa',
  'track_name': "Feelin' Myself",
  'genre': 'pop',
  'year': 2013},
 {'id': '26XUAwGZqQEyy8Ubhtj4kq',
  'artist_name': 'Mustard',
  'track_name': "Feelin' Myself",
  'genre': 'pop',
  'year': 2013},
 {'id': '7d1CFwrBmH34gmS0Hkbfbt',
  'artist_name': 'Zendaya',
  'track_name': 'Replay',
  'genre': 'pop',
  'year': 2013},
 {'id': '4pi0Elz7B7cLfw37J3bYm9',
  'artist_name': 'EXO',
  'track_name': 'Growl',
  'genre': 'pop',
  'year': 2013},
 {'id': '7GCElX2eJA5t0AFWw3WzKn',
  'artist_name': 'Katy Perry',
  'track_name': 'This Is How We Do',
  'genre': 'pop',
  'year': 2013},
 {'id': '1bumlOqo6y4hmPSVgRjPXi',
  'artist_name': 'Sergio Contreras',
  'track_name': 'Todos los besos',
  'genre': 'pop',
  'year': 2013},
 {'id': '4bLtrrVDspeDNSaHGGMQkB',
  'artist_name': 'BTS',
  'track_name': 'If I Ruled the World',
  'genre': 'pop',
  'year': 2013},
 {'id': '4jhrsCoNiei37ankpBSMOt',
  'artist_name': 'Carlos Baute',
  'track_name': 'En el buzón de tu corazón',
  'genre': 'pop',
  'year': 2013},
 {'id': '7dQGDSVjt1vS6BsDURjYhS',
  'artist_name': 'Bruno Mars',
  'track_name': 'Treasure - Cash Cash Radio Mix',
  'genre': 'pop',
  'year': 2013},
 {'id': '54X4tsc4YnvhliQQjP1T0V',
  'artist_name': 'DJ Antoine',
  'track_name': "You're Ma Cherie - DJ Antoine vs Mad Mark 2K13 Radio Edit",
  'genre': 'pop',
  'year': 2013},
 {'id': '54X4tsc4YnvhliQQjP1T0V',
  'artist_name': 'Pitbull',
  'track_name': "You're Ma Cherie - DJ Antoine vs Mad Mark 2K13 Radio Edit",
  'genre': 'pop',
  'year': 2013},
 {'id': '54X4tsc4YnvhliQQjP1T0V',
  'artist_name': 'Mad Mark',
  'track_name': "You're Ma Cherie - DJ Antoine vs Mad Mark 2K13 Radio Edit",
  'genre': 'pop',
  'year': 2013},
 {'id': '5aePqSLsPvdZYTqbuZJQnO',
  'artist_name': 'El Biri',
  'track_name': 'Tramposa',
  'genre': 'pop',
  'year': 2013},
 {'id': '3VlYMpSmYooLpzLiRBBfbX',
  'artist_name': 'BTS',
  'track_name': 'Paldogangsan',
  'genre': 'pop',
  'year': 2013},
 {'id': '5cghqtgljxpGJ1XeXAIK4p',
  'artist_name': 'Charli xcx',
  'track_name': 'You (Ha Ha Ha)',
  'genre': 'pop',
  'year': 2013},
 {'id': '2VNpT9fRk1kyksT0S4coZR',
  'artist_name': 'EXO',
  'track_name': 'The First Snow',
  'genre': 'pop',
  'year': 2013},
 {'id': '47rzxY9wSpomHE1gT94jIT',
  'artist_name': 'Ariana Grande',
  'track_name': 'Right There',
  'genre': 'pop',
  'year': 2013},
 {'id': '47rzxY9wSpomHE1gT94jIT',
  'artist_name': 'Big Sean',
  'track_name': 'Right There',
  'genre': 'pop',
  'year': 2013},
 {'id': '2OoLIJNxpsNs9wIHqWQrED',
  'artist_name': 'Lady Gaga',
  'track_name': 'Donatella',
  'genre': 'pop',
  'year': 2013},
 {'id': '2fDByLUAC1YsxbhgHGBqdg',
  'artist_name': 'Fly Project',
  'track_name': 'Toca Toca',
  'genre': 'pop',
  'year': 2013},
 {'id': '0JswmIBSn3XZ15wEEtH5fj',
  'artist_name': 'James Arthur',
  'track_name': 'Impossible - Acoustic',
  'genre': 'pop',
  'year': 2013},
 {'id': '29vOLabxvytbI8fX9xgTaD',
  'artist_name': 'BTS',
  'track_name': 'We On',
  'genre': 'pop',
  'year': 2013},
 {'id': '6vt0I1cw1YmAIKDJvHVIM5',
  'artist_name': 'Justin Timberlake',
  'track_name': 'Suit & Tie (feat. JAY-Z)',
  'genre': 'pop',
  'year': 2013},
 {'id': '6vt0I1cw1YmAIKDJvHVIM5',
  'artist_name': 'JAY-Z',
  'track_name': 'Suit & Tie (feat. JAY-Z)',
  'genre': 'pop',
  'year': 2013},
 {'id': '1ki575hbZbZ6nkBrfpzD0b',
  'artist_name': 'Gloria Trevi',
  'track_name': 'Habla Blah Blah',
  'genre': 'pop',
  'year': 2013},
 {'id': '1ki575hbZbZ6nkBrfpzD0b',
  'artist_name': 'Shy Carter',
  'track_name': 'Habla Blah Blah',
  'genre': 'pop',
  'year': 2013},
 {'id': '4EwNWRBWdZ6bgvxRHlZ8OO',
  'artist_name': 'G-DRAGON',
  'track_name': 'CROOKED',
  'genre': 'pop',
  'year': 2013},
 {'id': '04O2lYPszboATcwFyjF80O',
  'artist_name': 'Saad Lamjarred',
  'track_name': 'Mal Hbibi',
  'genre': 'pop',
  'year': 2013},
 {'id': '0WxS9Vw4649veGUtOrOPO1',
  'artist_name': 'Moderat',
  'track_name': 'Let in the Light',
  'genre': 'pop',
  'year': 2013},
 {'id': '6xJOhSm4SvZwzy3uhWz26O',
  'artist_name': 'Andrew Belle',
  'track_name': 'The Enemy',
  'genre': 'pop',
  'year': 2013},
 {'id': '2VL0W9x83RwQOBGbfphBqW',
  'artist_name': 'Carlos Vives',
  'track_name': 'La Foto de los Dos',
  'genre': 'pop',
  'year': 2013},
 {'id': '3KkbZok84es6JqI5aiLj1g',
  'artist_name': 'BTS',
  'track_name': 'BTS Cypher Pt.1',
  'genre': 'pop',
  'year': 2013},
 {'id': '30V0N0nJFHzKq5BXCWvF8O',
  'artist_name': 'JENCARLOS',
  'track_name': 'Dime',
  'genre': 'pop',
  'year': 2013},
 {'id': '0TPF6uW7fhMXJPoBERqTy5',
  'artist_name': 'All Time Low',
  'track_name': 'A Love Like War (feat. Vic Fuentes)',
  'genre': 'pop',
  'year': 2013},
 {'id': '0TPF6uW7fhMXJPoBERqTy5',
  'artist_name': 'Vic Fuentes',
  'track_name': 'A Love Like War (feat. Vic Fuentes)',
  'genre': 'pop',
  'year': 2013},
 {'id': '6dDIOU6AqgLkrjFNPgvKY6',
  'artist_name': 'Miley Cyrus',
  'track_name': 'FU (feat. French Montana)',
  'genre': 'pop',
  'year': 2013},
 {'id': '6dDIOU6AqgLkrjFNPgvKY6',
  'artist_name': 'French Montana',
  'track_name': 'FU (feat. French Montana)',
  'genre': 'pop',
  'year': 2013},
 {'id': '2QVXLAI2Io3tDmhFOSumr0',
  'artist_name': 'BTS',
  'track_name': 'Interlude',
  'genre': 'pop',
  'year': 2013},
 {'id': '2LAKLX6o1JzQJHUp8NIhLA',
  'artist_name': 'Renee Olstead',
  'track_name': 'Sleepwalk',
  'genre': 'pop',
  'year': 2013},
 {'id': '0jT7DDqYbpOik6iun6ydUL',
  'artist_name': 'Carlos Vives',
  'track_name': 'Como Le Gusta a Tu Cuerpo (feat. Michel Teló)',
  'genre': 'pop',
  'year': 2013},
 {'id': '0jT7DDqYbpOik6iun6ydUL',
  'artist_name': 'Michel Teló',
  'track_name': 'Como Le Gusta a Tu Cuerpo (feat. Michel Teló)',
  'genre': 'pop',
  'year': 2013},
 {'id': '4fJrqBOXrJ9QwaqJ9UsptN',
  'artist_name': 'Luiz Bonfá',
  'track_name': 'Sambalamento',
  'genre': 'pop',
  'year': 2013},
 {'id': '1UlnDZ5ubsSX3xrXu063dZ',
  'artist_name': 'BTS',
  'track_name': 'Intro: 2 Cool 4 Skool',
  'genre': 'pop',
  'year': 2013},
 {'id': '1UlnDZ5ubsSX3xrXu063dZ',
  'artist_name': 'dj friz',
  'track_name': 'Intro: 2 Cool 4 Skool',
  'genre': 'pop',
  'year': 2013},
 {'id': '7v4T4qeHh2Y8Rg7HQWaFSS',
  'artist_name': 'Lee Hyori',
  'track_name': 'Miss Korea',
  'genre': 'pop',
  'year': 2013},
 {'id': '0kS6GezxkbM5YXffQFnID6',
  'artist_name': 'Lady Gaga',
  'track_name': 'Sexxx Dreams',
  'genre': 'pop',
  'year': 2013},
 {'id': '6Gi3JimL6FXu2lkyTAIRxE',
  'artist_name': 'Reik',
  'track_name': 'Con la Cara en Alto',
  'genre': 'pop',
  'year': 2013},
 {'id': '6AviHKu3ydzAePBmzEi62v',
  'artist_name': 'MIKA',
  'track_name': 'Popular Song',
  'genre': 'pop',
  'year': 2013},
 {'id': '6AviHKu3ydzAePBmzEi62v',
  'artist_name': 'Ariana Grande',
  'track_name': 'Popular Song',
  'genre': 'pop',
  'year': 2013},
 {'id': '0D7eIgjWyydqcFBK4isTW2',
  'artist_name': 'INNA',
  'track_name': 'Inndia',
  'genre': 'pop',

In [44]:
type(canciones_pop_2010_2015)
len(canciones_pop_2010_2015)
canciones_pop_2010_2015[0]

{'id': '3U4isOIWM3VvDubwSI3y7a',
 'artist_name': 'John Legend',
 'track_name': 'All of Me',
 'genre': 'pop',
 'year': 2013}

In [26]:
artistas_set = set()

for canciones in canciones_pop_2010_2015:
    nombre = canciones.get("artist_name")
    if nombre:
        artistas_set.add(nombre.strip())

artistas = sorted(artistas_set)
print("Artistas únicos:", len(artistas))

Artistas únicos: 442

In [9]:
artistas_set

{'2 In A Room',
 '2001:Canarias',
 '2NE1',
 '2PM',
 '48th St. Collective',
 '4Minute',
 'A$AP Ferg',
 'AOA',
 'Abel Pintos',
 'Adele',
 'Aimer',
 'Akon',
 'Alana Marie',
 'Alejandro Sanz',
 'Aleks Syntek',
 'Alkilados',
 'All Time Low',
 'Ana Costa',
 'Anarbor',
 'Anastacia',
 'Andra Day',
 'Andrea Echeverri',
 'Andrew Belle',
 'Andrew Bird',
 'Andrés Cepeda',
 'Ane Brun',
 'Anitta',
 'Antonia',
 'Antonio José',
 'Antônio Carlos Jobim',
 'Arash',
 'Ariana Grande',
 'Ariel Camacho y Los Plebes Del Rancho',
 'Arrow Benjamin',
 'Astrud C',
 'Asu',
 'B.P.M. System',
 'B.o.B',
 'BANKS',
 'BIGBANG',
 'BTS',
 'Basshunter',
 'Becky',
 "Beluga's Trio",
 'Benjamin Clementine',
 'Beyoncé',
 'Big Sean',
 'Bigal & L Jake',
 'Birdman',
 'Birdy',
 'Block B',
 'Blood Orange',
 'Boby',
 'Bogdan Artistu',
 'Bossa Curve',
 'Bossanatics',
 'Brian Cross',
 'Britney Spears',
 'Bruno Mars',
 'CL',
 'Cabas',
 'Cali Y El Dandee',
 'Calibre 50',
 'Camila',
 'Camila Cabello',
 'Carlos Baute',
 'Carlos Vives',
 'Carly Rae Jepsen',
 'Caroline Pennell',
 'Caroline Polachek',
 'Cascada',
 'Cashmere Cat',
 'Cassandra Beck',
 'Celso Mendes',
 'Charli xcx',
 'Chasing Grace',
 'Chayanne',
 'Cher Lloyd',
 'Childish Gambino',
 'Chino & Nacho',
 'ChocQuibTown',
 'Cholo Valderrama',
 'Chris Brown',
 'Christina Aguilera',
 'Christina Perri',
 'Coldplay',
 'Coral Group',
 'Costa Azul Quartet',
 'Cristi Dules',
 'Cristian Castro',
 'DJ Antoine',
 'DJ BoBo',
 'DJ Ötzi',
 'DJane HouseKat',
 'Daddy Yankee',
 'Daily Planet',
 'Daniela Maia',
 'David Barrull',
 'David Bisbal',
 'David Guetta',
 'Demi Lovato',
 'Denisa',
 'Diana Martinez',
 'Dinah Eastwood',
 'Disko Warp',
 'Doe B.',
 'Drake',
 'Dua Lipa',
 'EXID',
 'EXO',
 'EXO-K',
 'Ed Sheeran',
 'Edward Maya',
 'El Arrebato',
 'El Barrio',
 'El Biri',
 'El Cuarteto De Nos',
 'El Suso',
 'Ellie Goulding',
 'Elvis Crespo',
 'Emeli Sandé',
 'Enrique Iglesias',
 'Estopa',
 'Eve St. Jones',
 'Evelyn Thomas',
 'FKA twigs',
 'Fanny Lu',
 'Fantasy Project feat. NDA',
 'Fat Synth',
 'Fetty Wap',
 'Fiesta Pop',
 'Flo Rida',
 'Florence + The Machine',
 'Florin Salam',
 'Fly Project',
 'Fondo Flamenco',
 'Fonseca',
 'Foxygen',
 'Francesco Yates',
 'Franco Sattamini',
 'Freeway',
 'French Montana',
 'Future',
 'G-DRAGON',
 'G-Eazy',
 'G.E.M.',
 'GD X TAEYANG',
 'GFRIEND',
 'GOT7',
 'Generis',
 'George Ezra',
 "Gigi D'Agostino",
 'Gilberto Gil',
 "Girl's Day",
 "Girls' Generation",
 'Gloria Trevi',
 'Gonzalo',
 'Gregory Porter',
 'Grimes',
 'Grupo Exterminador',
 'Ha*Ash',
 'Hanson',
 'Helene Fischer',
 'Herencia de Timbiqui',
 'High Density',
 'Holly Walker',
 'Hozier',
 'Hype',
 'INNA',
 'Icona Pop',
 'Iggy Azalea',
 'Iggy Pop',
 'Ilsey',
 'India Martinez',
 'ItaloBrothers',
 'Ituana',
 'J Alvarez',
 'J Balvin',
 'J.D.B',
 'JAY-Z',
 'JENCARLOS',
 'JENNIE',
 'JJ Lin',
 'James Arthur',
 'James Bay',
 'Jamie Lawson',
 'Jasmine Thompson',
 'Jason Derulo',
 'Jason Mraz',
 'Javed Bashir',
 'Jay Park',
 'Jennifer Lopez',
 'Jerry Daley',
 'Jess Glynne',
 'Jesse',
 'Jesse & Joy',
 'Jessie J',
 'Joey Galaxy',
 'John Legend',
 'John Ryan',
 'Joker Xue',
 'Juan Luis Guerra 4.40',
 'Juanes',
 'Juanlu Montoya',
 'Julieta Venegas',
 'Junco',
 'Junggigo',
 'Junior Caldera',
 'Just Blaze',
 'Justin Bieber',
 'Justin Timberlake',
 'KYANU',
 'Kamembert',
 'Kany García',
 'Kanye West',
 'Katy Perry',
 'Kelly Clarkson',
 'Kendrick Lamar',
 'Kesha',
 'Kevin Gates',
 'Khalil Fong',
 'Kid Cudi',
 'Kid Ink',
 'Kike Boy',
 'Kina Grannis',
 'Kodaline',
 'Korpus',
 'Kovacs',
 'Kriss',
 'Kryss',
 'La Húngara',
 "La K'onga",
 'La Oreja de Van Gogh',
 'Lady Gaga',
 'Laura Pausini',
 'Laury "La Hungarilla"',
 'Lee Hyori',
 'Leon Bridges',
 'Lianne La Havas',
 'Lil Wayne',
 'Lilly Wood and The Prick',
 'Lily Allen',
 'Lindsey Stirling',
 'Little Mix',
 'Liviu Guta',
 'London Grammar',
 'Lorde',
 'Loreen',
 'Los Caños',
 'Los Flechazos',
 'Los Rebujitos',
 'Lucas Arnau',
 'Lucian Printu',
 'Luis Fonsi',
 'Luiz Bonfá',
 'MARINA',
 'MIKA',
 'MINO',
 'MONSTA X',
 'Mac Miller',
 'Mack Maine',
 'Mad Mark',
 'Madonna',
 'Maki',
 'Maluma',
 'Manuel Medrano',
 'Manuel Álvarez Fernández',
 'Maná',
 'Marc Anthony',
 'Marco Antonio Solís',
 'Margo Guryan',
 'Marian Hill',
 'Maribou State',
 'Marina',
 'Mark Ronson',
 'Maroon 5',
 'María Artés',
 'Massey',
 'Matisse',
 'Max Him',
 'McFly',
 'Megabass',
 'Meghan Trainor',
 'Memphis Bleek',
 'Men Without Hats',
 'Michael Bublé',
 'Michel Teló',
 'Midiland',
 'Miguel Bosé',
 'Miguel Campello',
 'Mike Bahía',
 'Miley Cyrus',
 'Moderat',
 'Molly Nilsson',
 'Monty',
 'Morat',
 'Mr Jones Machine',
 'Mr. Juve',
 'Mustard',
 'Nani Cortés',
 'Nas',
 'Natascha',
 'Naughty Boy',
 'Nick Jonas',
 'Nick Mulvey',
 'Nicki Minaj',
 'Nicolae Guta',
 'Nicolas Mayorca',
 'Nils Landgren',
 'Nina Simone',
 'Niña Pastori',
 'Nolasco',
 'Nova Jazzers',
 'Ofenbach',
 'Olly Murs',
 'Omega',
 'Ophélie Gaillard',
 'Orange Caramel',
 'Otilia',
 'PSY',
 'Pablo Alborán',
 'Paramore',
 'Passenger',
 'Pastora Soler',
 'Paul McCartney',
 'Peter Polycarpou',
 'Pets Tseng',
 'Pharrell Williams',
 'Pink Martini',
 'Pitbull',
 'Pitingo',
 'Pritam',
 'RHODES',
 'Rajat Arora',
 'Rameez',
 'Red Velvet',
 'Reik',
 'Remo the Hitmaker',
 'Renee Olstead',
 'Ricardo Arjona',
 'Ricardo Autobahn',
 'Rich Gang',
 'Ricky Martin',
 'Rihanna',
 'Rita Ora',
 'Robin McKelle & The Flytones',
 'Robin Schulz',
 'Robin Thicke',
 'Robyn',
 'Rodríguez',
 'Romain Lécuyer',
 'Rudimental',
 'Ruth B.',
 'Röyksopp',
 'SEREBRO',
 'SOYOU',
 'SUNMI',
 'Saad Lamjarred',
 'Sam Martin',
 'Sam Smith',
 'Sara Bareilles',
 'Sarah Menescal',
 'Sarayma',
 'Scubba',
 'Sean Paul',
 'Selena Gomez',
 'Sergio Contreras',
 'Sergio Dalma',
 'Shakira',
 'Shawn Mendes',
 'Shy Carter',
 'Sia',
 'Silver Pozzoli',
 'Silvestre Dangond',
 "Sonia O'Hara",
 'Sophie Ellis-Bextor',
 'Squeeze',
 'St. Paul & The Broken Bones',
 'Stephenie Coker',
 'Stereo Dub',
 'Studio Rio',
 'Sukima Switch',
 'Supreme Boi',
 'System',
 'T-Pain',
 'T.I.',
 'T.O.P.',
 'TAEYANG',
 'TWICE',
 'Taylor Swift',
 'Tess',
 'Thalia',
 'The Avener',
 'The Cooltrane Quartet',
 'The Nativos',
 'The New Division',
 'The Style Council',
 'The WAV.s',
 'The Weeknd',
 'Tinashe',
 'Toco',
 'Tom Boxer',
 'Tomasito',
 'Too $hort',
 'Toquinho',
 'Tove Lo',
 'Traviezoz de la Zierra',
 'Twista',
 'Ty Dolla $ign',
 'Tyler Ward',
 'Tyler, The Creator',
 'Ugly Duck',
 'Ulises Bueno',
 'United Rhythms Of Brazil',
 'Urban Love',
 'Valeria',
 'Vali Vijelie',
 'Vanesa Martín',
 'Verdine White',
 'Vic Fuentes',
 'Victor Peixeiro',
 'Vika Jigulina',
 'Villamizar',
 'Vinícius',
 'Vinícius de Moraes',
 'Visage',
 'Vulfpeck',
 'Wiz Khalifa',
 'Wonder Girls',
 'Xenturion Prime',
 'Yuridia',
 'Yurie Kokubu',
 'ZICO',
 'Zedd',
 'Zendaya',
 'Zone Tripper',
 'dj friz',
 'lIlBOI',
 'lavi kou',
 'miss A',
 'moana',
 'will.i.am'}

## Extracción de información de Artistas en Last FM

In [27]:
from dotenv import load_dotenv
load_dotenv()

api_key = os.getenv("api_key") # accedemos a la variable api_key que está en el archivo .env

In [29]:
# buscar el endpoint que nos interesa --> 
# codigo de prueba con 1 solo artista

datos_artista = []

for artista in ['Adele']:
    url = "https://ws.audioscrobbler.com/2.0/"

    llamada = requests.get(url, params={'api_key': api_key,
                                        'method': 'artist.getinfo',
                                        'artist': {artista},
                                        'format': 'json'})
    datos = llamada.json()
    datos_artista.append(datos)

In [30]:
datos

{'artist': {'name': 'Adele',
  'mbid': 'cc2c9c3c-b7bc-4b8b-84d8-4fbd8779e493',
  'url': 'https://www.last.fm/music/Adele',
  'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'small'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'medium'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'large'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'extralarge'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'mega'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': ''}],
  'streamable': '0',
  'ontour': '0',
  'stats': {'listeners': '5552330', 'playcount': '314157643'},
  'similar': {'artist': [{'name': 'Sam Smith',
     'url': 'https://www.last.fm/music/Sam+Smith',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Whitney Houston',
     'url': 'https://www.last.fm/music/Whitney+Houston',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Sia',
     'url': 'https://www.last.fm/music/Sia',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Beyoncé',
     'url': 'https://www.last.fm/music/Beyonc%C3%A9',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Amy Winehouse',
     'url': 'https://www.last.fm/music/Amy+Winehouse',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]}]},
  'tags': {'tag': [{'name': 'soul', 'url': 'https://www.last.fm/tag/soul'},
    {'name': 'female vocalists',
     'url': 'https://www.last.fm/tag/female+vocalists'},
    {'name': 'british', 'url': 'https://www.last.fm/tag/british'},
    {'name': 'singer-songwriter',
     'url': 'https://www.last.fm/tag/singer-songwriter'},
    {'name': 'indie', 'url': 'https://www.last.fm/tag/indie'}]},
  'bio': {'links': {'link': {'#text': '',
     'rel': 'original',
     'href': 'https://last.fm/music/Adele/+wiki'}},
   'published': '24 Nov 2006, 21:07',
   'summary': 'Adele Laurie Blue Adkins MBE (born May 5, 1988) is an English singer and songwriter. After graduating in arts from the BRIT School in 2006, Adele signed a record deal with XL Recordings. Her debut album, 19, was released in 2008 and spawned the UK top-five singles "Chasing Pavements" and "Make You Feel My Love". The album was certified 8× platinum in the UK and triple platinum in the US. Adele was honoured with the Brit Award for Rising Star as well as the Grammy Award for Best New Artist. <a href="https://www.last.fm/music/Adele">Read more on Last.fm</a>',
   'content': 'Adele Laurie Blue Adkins MBE (born May 5, 1988) is an English singer and songwriter. After graduating in arts from the BRIT School in 2006, Adele signed a record deal with XL Recordings. Her debut album, 19, was released in 2008 and spawned the UK top-five singles "Chasing Pavements" and "Make You Feel My Love". The album was certified 8× platinum in the UK and triple platinum in the US. Adele was honoured with the Brit Award for Rising Star as well as the Grammy Award for Best New Artist.\n\nAdele released her second studio album, 21, in 2011. It became the world\'s best-selling album of the 21st century, with sales of over 31 million copies. It was certified 17× platinum in the UK (the highest by a solo artist of all time) and Diamond in the US. According to Billboard, 21 is the top-performing album in the US chart history, topping the Billboard 200 for 24 weeks (the longest for a female artist ever). She was the first female artist in the history of the Billboard Hot 100 to have three simultaneous top-ten singles as a lead artist, with "Rolling in the Deep", "Someone Like You" and "Set Fire to the Rain", all of which also topped the chart. The album received a record-tying six Grammy Awards, including Album of the Year, and the Brit Award for British Album of the Year. The success of 21 earned Adele numerous mentions in the Guinness Book of Records.\n\nIn 2012, Adele released "Skyfall", a soundtrack single for the James Bond film of the same name, which won the Academy Award and the Golden Globe Award for Best Original Song. Her third studio album, 25, was released in 2015 and became the year\'s best-selling album and broke first-week sales records in the UK and US. 25 was her second album to be certified Diamond in the US and earned her five Grammy Awards, including Album of the Year, and four Brit Awards, including British Album of the Year. The lead single, "Hello", became the first song in the US to sell over one million digital copies within a week of its release. Her fourth studio album 30, which contains the chart-topping single "Easy on Me", was released in 2021 and became the year\'s best-selling album worldwide including US and UK. 30 won the 2022 Brit Award for British Album of the Year.\n\nAdele is one of the world\'s best-selling music artists, with sales of over 120 million records. Her accolades include fifteen Grammy Awards and twelve Brit Awards. In 2011, 2012, and 2016, Billboard named her Artist of the Year. At the 2012 and 2016 Ivor Novello Awards, Adele was named Songwriter of the Year by the British Academy of Songwriters, Composers, and Authors. In 2012, she was listed at number five on VH1\'s 100 Greatest Women in Music. Time magazine named her one of the most influential people in the world in 2012, 2016, and 2022. She was appointed a MBE at the 2013 Queen\'s Birthday Honours for services to music. Her third tour saw her break attendance records globally, including in the UK, Australia, and the US, and her album 21 has been listed in Rolling Stone\'s 500 Greatest Albums of All Time (2020). <a href="https://www.last.fm/music/Adele">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}}}

In [10]:
for elemento in datos_artista:
    print(elemento['artist'].keys())

dict_keys(['name', 'mbid', 'url', 'image', 'streamable', 'ontour', 'stats', 'similar', 'tags', 'bio'])

In [35]:
import re

In [36]:
def limpiar_summary(texto):
    if not texto:
        return None

    # Eliminar etiquetas HTML
    texto = re.sub(r"<.*?>", "", texto)

    # Eliminar saltos de línea
    texto = texto.replace("\n", " ")

    # Eliminar espacios múltiples
    texto = re.sub(r"\s+", " ", texto)

    # Eliminar coletilla típica de Last.fm
    texto = texto.replace("Read more on Last.fm", "")

    return texto.strip()

In [37]:
info_limpia = []

for elemento in datos_artista:

    if "artist" not in elemento:
        continue

    artista = elemento["artist"]

    similares = artista.get("similar", {}).get("artist", [])
    nombres_similares = [a.get("name") for a in similares]

    resumen_limpio = limpiar_summary(
        artista.get("bio", {}).get("summary")
    )

    info_limpia.append({
        "artist_name": artista.get("name"),
        "bio_summary": resumen_limpio,
        "listeners": artista.get("stats", {}).get("listeners"),
        "playcount": artista.get("stats", {}).get("playcount"),
        "similar_artists": nombres_similares
    })

In [38]:
info_limpia

[{'artist_name': 'Adele',
  'bio_summary': 'Adele Laurie Blue Adkins MBE (born May 5, 1988) is an English singer and songwriter. After graduating in arts from the BRIT School in 2006, Adele signed a record deal with XL Recordings. Her debut album, 19, was released in 2008 and spawned the UK top-five singles "Chasing Pavements" and "Make You Feel My Love". The album was certified 8× platinum in the UK and triple platinum in the US. Adele was honoured with the Brit Award for Rising Star as well as the Grammy Award for Best New Artist.',
  'listeners': '5552330',
  'playcount': '314157643',
  'similar_artists': ['Sam Smith',
   'Whitney Houston',
   'Sia',
   'Beyoncé',
   'Amy Winehouse']}]

## Ahora con la lista entera de artistas

In [41]:
import time
import requests

def obtener_artista(nombre, api_key, reintentos=2, timeout=10):

    for intento in range(reintentos + 1):
        try:
            response = requests.get(
                "https://ws.audioscrobbler.com/2.0/",
                headers={"User-Agent": "adalab-project"},
                params={
                    "method": "artist.getinfo",
                    "artist": nombre,
                    "api_key": api_key,
                    "format": "json"
                },
                timeout=timeout
            )

            if response.status_code == 200:
                return response.json()

        except requests.exceptions.Timeout:
            if intento < reintentos:
                time.sleep(1)  # backoff
            else:
                print(f"Timeout definitivo con {nombre}")
                return None

        except requests.exceptions.RequestException as e:
            print(f"Error con {nombre}: {e}")
            return None

In [42]:
info_limpia = []

for artista_nombre in artistas_set:

    print(f"Procesando: {artista_nombre}")

    data = obtener_artista(artista_nombre, api_key)

    if not data or "artist" not in data:
        continue

    artista = data["artist"]

    similares = artista.get("similar", {}).get("artist", [])
    nombres_similares = [a.get("name") for a in similares]

    resumen_limpio = limpiar_summary(
        artista.get("bio", {}).get("summary")
    )

    info_limpia.append({
        "artist_name": artista.get("name"),
        "bio_summary": resumen_limpio,
        "listeners": artista.get("stats", {}).get("listeners"),
        "playcount": artista.get("stats", {}).get("playcount"),
        "similar_artists": nombres_similares
    })

    time.sleep(0.2)

Procesando: EXID
Procesando: George Ezra
Procesando: David Barrull
Procesando: Mr Jones Machine
Procesando: Chris Brown
Procesando: Antônio Carlos Jobim
Procesando: Bogdan Artistu
Procesando: Ane Brun
Procesando: Fantasy Project feat. NDA
Procesando: moana
Procesando: Aimer
Procesando: T.O.P.
Procesando: Junco
Procesando: Herencia de Timbiqui
Procesando: Christina Aguilera
Procesando: Future
Procesando: T-Pain
Procesando: Kamembert
Procesando: Childish Gambino
Procesando: El Biri
Procesando: Birdman
Procesando: Olly Murs
Procesando: Saad Lamjarred
Procesando: Sam Smith
Procesando: Chino & Nacho
Procesando: Girl's Day
Procesando: Matisse
Procesando: Fanny Lu
Procesando: Bossa Curve
Procesando: Miley Cyrus
Procesando: Bigal & L Jake
Procesando: Tom Boxer
Procesando: Pitbull
Procesando: Franco Sattamini
Procesando: Renee Olstead
Procesando: PSY
Procesando: Fat Synth
Procesando: Vinícius
Procesando: Robin McKelle & The Flytones
Procesando: Squeeze
Procesando: Estopa
Procesando: Sara Bareilles
Procesando: Maribou State
Procesando: Silver Pozzoli
Procesando: Doe B.
Procesando: Kovacs
Procesando: Michael Bublé
Procesando: B.o.B
Procesando: Charli xcx
Procesando: Zone Tripper
Procesando: Bruno Mars
Procesando: Cashmere Cat
Procesando: DJ BoBo
Procesando: Block B
Procesando: Rajat Arora
Procesando: Toco
Procesando: ChocQuibTown
Procesando: James Arthur
Procesando: Vinícius de Moraes
Procesando: Holly Walker
Procesando: Juanes
Procesando: Ty Dolla $ign
Procesando: 2 In A Room
Procesando: Elvis Crespo
Procesando: Maki
Procesando: SOYOU
Procesando: Cali Y El Dandee
Procesando: AOA
Procesando: Helene Fischer
Procesando: Carlos Vives
Procesando: JENNIE
Procesando: Anarbor
Procesando: Jasmine Thompson
Procesando: Pets Tseng
Procesando: Mike Bahía
Procesando: Tomasito
Procesando: Coldplay
Procesando: Robyn
Procesando: Christina Perri
Procesando: Andrew Bird
Procesando: The Weeknd
Procesando: French Montana
Procesando: Gigi D'Agostino
Procesando: 2001:Canarias
Procesando: Shy Carter
Procesando: Omega
Procesando: Pink Martini
Procesando: Nick Jonas
Procesando: Maluma
Procesando: Sukima Switch
Procesando: Nicolas Mayorca
Procesando: Ha*Ash
Procesando: DJane HouseKat
Procesando: Sam Martin
Procesando: Shakira
Procesando: Alkilados
Procesando: Toquinho
Procesando: 2PM
Procesando: Beluga's Trio
Procesando: Justin Bieber
Procesando: BANKS
Procesando: Mr. Juve
Procesando: Benjamin Clementine
Procesando: Nick Mulvey
Procesando: Nicki Minaj
Procesando: Alejandro Sanz
Procesando: Freeway
Procesando: Florence + The Machine
Procesando: Fondo Flamenco
Procesando: Reik
Procesando: Emeli Sandé
Procesando: Lucian Printu
Procesando: Xenturion Prime
Procesando: Joey Galaxy
Procesando: Megabass
Procesando: El Arrebato
Procesando: El Cuarteto De Nos
Procesando: DJ Antoine
Procesando: Becky
Procesando: Pharrell Williams
Procesando: Red Velvet
Procesando: Sophie Ellis-Bextor
Procesando: Andrew Belle
Procesando: Jay Park
Procesando: Tyler Ward
Procesando: Hype
Procesando: Cholo Valderrama
Procesando: Shawn Mendes
Procesando: RHODES
Procesando: Brian Cross
Procesando: Kike Boy
Procesando: Jamie Lawson
Procesando: Sarayma
Procesando: lavi kou
Procesando: Andrés Cepeda
Procesando: Morat
Procesando: Laury "La Hungarilla"
Procesando: Little Mix
Procesando: Junior Caldera
Procesando: Los Rebujitos
Procesando: Lorde
Procesando: Gregory Porter
Procesando: Tove Lo
Procesando: Taylor Swift
Procesando: La Húngara
Procesando: Anitta
Procesando: Loreen
Procesando: MINO
Procesando: Camila
Procesando: MIKA
Procesando: Beyoncé
Procesando: Stereo Dub
Procesando: Molly Nilsson
Procesando: GD X TAEYANG
Procesando: Kodaline
Procesando: Aleks Syntek
Procesando: Vulfpeck
Procesando: Celso Mendes
Procesando: ItaloBrothers
Procesando: Laura Pausini
Procesando: 2NE1
Procesando: Britney Spears
Procesando: Kid Ink
Procesando: Foxygen
Procesando: Rameez
Procesando: Calibre 50
Procesando: Asu
Procesando: Jason Derulo
Procesando: SEREBRO
Procesando: Cristian Castro
Procesando: Ricardo Autobahn
Procesando: Midiland
Procesando: BTS
Procesando: Ruth B.
Procesando: Maroon 5
Procesando: Natascha
Procesando: Juanlu Montoya
Procesando: El Suso
Procesando: London Grammar
Procesando: Carly Rae Jepsen
Procesando: Jennifer Lopez
Procesando: BIGBANG
Procesando: Miguel Bosé
Procesando: Ofenbach
Procesando: Madonna
Procesando: All Time Low
Procesando: The WAV.s
Procesando: Leon Bridges
Procesando: Ulises Bueno
Procesando: Silvestre Dangond
Procesando: Abel Pintos
Procesando: Paramore
Procesando: Lee Hyori
Procesando: Ilsey
Procesando: Mustard
Procesando: Kid Cudi
Procesando: Fly Project
Procesando: Wonder Girls
Procesando: Tyler, The Creator
Procesando: Mad Mark
Procesando: Kanye West
Procesando: The Style Council
Procesando: The Avener
Procesando: Cassandra Beck
Procesando: Adele
Procesando: Daniela Maia
Procesando: Manuel Medrano
Procesando: Nas
Procesando: Eve St. Jones
Procesando: Evelyn Thomas
Procesando: Luis Fonsi
Procesando: Yuridia
Procesando: Liviu Guta
Procesando: Valeria
Procesando: EXO
Procesando: Bossanatics
Procesando: Peter Polycarpou
Procesando: Nils Landgren
Procesando: Antonio José
Procesando: Drake
Procesando: Grimes
Procesando: Lianne La Havas
Procesando: Supreme Boi
Procesando: Monty
Procesando: Marc Anthony
Procesando: Blood Orange
Procesando: Nani Cortés
Procesando: Ituana
Procesando: G.E.M.
Procesando: Just Blaze
Procesando: A$AP Ferg
Procesando: Juan Luis Guerra 4.40
Procesando: Lindsey Stirling
Procesando: Cher Lloyd
Procesando: Scubba
Procesando: The Cooltrane Quartet
Procesando: Iggy Azalea
Procesando: Sia
Procesando: Jesse
Procesando: Lily Allen
Procesando: Denisa
Procesando: McFly
Procesando: Daily Planet
Procesando: Demi Lovato
Procesando: Kelly Clarkson
Procesando: Manuel Álvarez Fernández
Procesando: TWICE
Procesando: Hanson
Procesando: Dua Lipa
Procesando: Sarah Menescal
Procesando: John Ryan
Procesando: Kriss
Procesando: Ellie Goulding
Procesando: Ana Costa
Procesando: La K'onga
Procesando: Birdy
Procesando: Lucas Arnau
Procesando: Max Him
Procesando: Chasing Grace
Procesando: Jesse & Joy
Procesando: ZICO
Procesando: Otilia
Procesando: JENCARLOS
Procesando: Rudimental
Procesando: Stephenie Coker
Procesando: Kevin Gates
Procesando: Jerry Daley
Procesando: Andra Day
Procesando: Anastacia
Procesando: Yurie Kokubu
Procesando: Cascada
Procesando: J.D.B
Procesando: G-Eazy
Procesando: TAEYANG
Procesando: Naughty Boy
Procesando: Antonia
Procesando: Generis
Procesando: David Bisbal
Procesando: Verdine White
Procesando: will.i.am
Procesando: Marina
Procesando: Grupo Exterminador
Procesando: Zendaya
Procesando: Meghan Trainor
Procesando: Mac Miller
Procesando: Big Sean
Procesando: GFRIEND
Procesando: Daddy Yankee
Procesando: Iggy Pop
Procesando: Miguel Campello
Procesando: Camila Cabello
Procesando: Julieta Venegas
Procesando: David Guetta
Procesando: JJ Lin
Procesando: MONSTA X
Procesando: India Martinez
Procesando: Traviezoz de la Zierra
Procesando: Cabas
Procesando: Carlos Baute
Procesando: Gilberto Gil
Procesando: Michel Teló
Procesando: J Balvin
Procesando: Paul McCartney
Procesando: Kany García
Procesando: G-DRAGON
Procesando: La Oreja de Van Gogh
Procesando: Nicolae Guta
Procesando: Rihanna
Procesando: St. Paul & The Broken Bones
Procesando: Too $hort
Procesando: High Density
Procesando: Margo Guryan
Procesando: Astrud C
Procesando: Massey
Procesando: Ricky Martin
Procesando: Katy Perry
Procesando: Lady Gaga
Procesando: 48th St. Collective
Procesando: Caroline Polachek
Procesando: T.I.
Procesando: Tess
Procesando: Francesco Yates
Procesando: Edward Maya
Procesando: GOT7
Procesando: Fetty Wap
Procesando: María Artés
Procesando: Junggigo
Procesando: Ophélie Gaillard
Procesando: Romain Lécuyer
Procesando: Diana Martinez
Procesando: System
Procesando: The Nativos
Procesando: Moderat
Procesando: Pastora Soler
Procesando: Röyksopp
Procesando: Sonia O'Hara
Procesando: Robin Thicke
Procesando: Ariana Grande
Procesando: Men Without Hats
Procesando: Los Flechazos
Procesando: Ricardo Arjona
Procesando: Enrique Iglesias
Procesando: Chayanne
Procesando: Lilly Wood and The Prick
Procesando: Pitingo
Procesando: Vali Vijelie
Procesando: Selena Gomez
Procesando: lIlBOI
Procesando: Girls' Generation
Procesando: FKA twigs
Procesando: Icona Pop
Procesando: Niña Pastori
Procesando: Passenger
Procesando: Nina Simone
Procesando: Fonseca
Procesando: Tinashe
Procesando: Kendrick Lamar
Procesando: Kina Grannis
Procesando: Luiz Bonfá
Procesando: Cristi Dules
Procesando: John Legend
Procesando: Ugly Duck
Procesando: Gonzalo
Procesando: Arrow Benjamin
Procesando: Maná
Procesando: Pablo Alborán
Procesando: Sean Paul
Procesando: Rich Gang
Procesando: Orange Caramel
Procesando: Vika Jigulina
Procesando: Rodríguez
Procesando: Ariel Camacho y Los Plebes Del Rancho
Procesando: Mark Ronson
Procesando: Wiz Khalifa
Procesando: Kryss
Procesando: Boby
Procesando: Sergio Contreras
Procesando: United Rhythms Of Brazil
Procesando: Rita Ora
Procesando: Zedd
Procesando: Basshunter
Procesando: Marco Antonio Solís
Procesando: Kesha
Procesando: Victor Peixeiro
Procesando: Mack Maine
Procesando: J Alvarez
Procesando: Pritam
Procesando: Coral Group
Procesando: Andrea Echeverri
Procesando: Thalia
Procesando: SUNMI
Procesando: Ed Sheeran
Procesando: Studio Rio
Procesando: Hozier
Procesando: CL
Procesando: Alana Marie
Procesando: Justin Timberlake
Procesando: James Bay
Procesando: Dinah Eastwood
Procesando: 4Minute
Procesando: Los Caños
Procesando: Lil Wayne
Procesando: Marian Hill
Procesando: The New Division
Procesando: Villamizar
Procesando: Joker Xue
Procesando: KYANU
Procesando: INNA
Procesando: Jessie J
Procesando: Jess Glynne
Procesando: Urban Love
Procesando: Visage
Procesando: Disko Warp
Procesando: Jason Mraz
Procesando: Costa Azul Quartet
Procesando: Twista
Procesando: dj friz
Procesando: Javed Bashir
Procesando: Gloria Trevi
Procesando: Florin Salam
Procesando: El Barrio
Procesando: Fiesta Pop
Procesando: EXO-K
Procesando: miss A
Procesando: Caroline Pennell
Procesando: Flo Rida
Procesando: Robin Schulz
Procesando: JAY-Z
Procesando: Arash
Procesando: DJ Ötzi
Procesando: MARINA
Procesando: Akon
Procesando: Korpus
Procesando: Sergio Dalma
Procesando: Vanesa Martín
Procesando: Khalil Fong
Procesando: Memphis Bleek
Procesando: Nolasco
Procesando: Vic Fuentes
Procesando: Remo the Hitmaker
Procesando: Nova Jazzers
Procesando: B.P.M. System

In [43]:
print(len(info_limpia))
print(len(artistas_set))

438
442

## Limpieza final y guardar a CSV

In [ ]:
df_canciones_pop = pd.DataFrame(canciones_pop_2010_2015)           # lista de canciones

In [53]:
df_canciones_pop

,id,artist_name,track_name,genre,year
0,3U4isOIWM3VvDubwSI3y7a,John Legend,All of Me,pop,2013
1,6Al0Kpd4VrRZ0Z4kTThNPa,Carlos Vives,Volví a Nacer,pop,2013
2,3ozuHMral4k7ALNOgPdxQ8,La Oreja de Van Gogh,El Primer Día del Resto de Mi Vida - Directo P...,pop,2013
3,26Z2FQ9KFswyX2x7LxhQKs,INNA,Caliente,pop,2013
4,2XHzzp1j4IfTNp1FTn7YFg,Lil Wayne,Love Me,pop,2013
...,...,...,...,...,...
845,3ob8TbTdg3zm0fe5KCGg30,Fat Synth,Secret,pop,2015
846,2dU2I8cJAvg4v9uTKWmoot,Generis,Dreams,pop,2015
847,20WRbAfJhdDpY5iP2xfCI3,Fiesta Pop,Año 2000,pop,2015
848,4VoHWTKwdeejTOEDXG1QCc,Fiesta Pop,A Quien Le Importa,pop,2015
849,0il4GDOrhu9x0NXboG5P7V,Korpus,Indie,pop,2015

In [54]:
df_canciones_pop.to_csv(
    "caciones_pop_2013_2015.csv",
    index=False,
    encoding="utf-8"
)

In [59]:
# lista de artistas con su summary, listeners, playcount

artistas_data = []

for artista in info_limpia:
    artistas_data.append({
        "artist_name": artista["artist_name"],
        "listeners": artista["listeners"],
        "playcount": artista["playcount"],
        "bio_summary": artista["bio_summary"]
    })

In [61]:
df_artistas = pd.DataFrame(artistas_data)

df_artistas

,artist_name,listeners,playcount,bio_summary
0,EXID,451046,21327169,EXID are a five-member South Korean girl group...
1,George Ezra,1431693,31770093,George Ezra (full name George Ezra Barnett) is...
2,David Barrull,2418,20351,
3,Mr Jones Machine,8341,107492,As possibly Sweden's finest synthpop act you f...
4,Chris Brown,4709986,155522558,"Christopher Maurice Brown (born May 5, 1989) i..."
...,...,...,...,...
433,Nolasco,14363,105219,
434,Vic Fuentes,446,2578,Vic Fuentes is the lead singer of Pierce The V...
435,Remo the Hitmaker,880,6127,
436,Nova Jazzers,10540,44845,
437,B.P.M. System,1409,6747,

In [ ]:
df_artistas.to_csv(
    "artists_pop.csv",
    index=False,
    encoding="utf-8"
)

In [63]:
similar_data = []

for artista in info_limpia:
    artista_principal = artista["artist_name"]

    for similar in artista["similar_artists"]:
        similar_data.append({
            "artist_name": artista_principal,
            "similar_artist_name": similar
        })

In [64]:
df_similar = pd.DataFrame(similar_data)

df_similar

        artist_name similar_artist_name
0              EXID                 AOA
1              EXID              SISTAR
2              EXID                 CLC
3              EXID          Girl's Day
4              EXID             4minute
...             ...                 ...
2075  B.P.M. System            Lady Gee
2076  B.P.M. System            Kike Boy
2077  B.P.M. System               Kryss
2078  B.P.M. System           New Limit
2079  B.P.M. System          Interfront

[2080 rows x 2 columns]

In [ ]:
df_similar.to_csv(
    "artista_similar_pop.csv",
    index=False,
    encoding="utf-8"
)